### ISSUE TITLE
Use #defines for switching to unprefixed versions 

### ISSUE THREAD

**Issue by orta** [hamcrest/OCHamcrest#62]
Hello! 

Future builds of OCHamcrest will end up being built as frameworks in CocoaPods, the downside of this for you is that `#defines` in the app itself don't affect the building of the framework now. This means the 
`#define HC_SHORTHAND` cannot affect the syntax of a given framework. For `specta/expecta` - I've recommend switching to the opposite ref: https://github.com/specta/expecta/issues/124

**Comment by jonreid** [comment]
How it's done in Quick: https://github.com/Quick/Quick/blob/a67d4ca077778f05792803d16d45da9064001dcd/Quick/DSL/QCKDSL.h

**Comment by jonreid** [comment]
First steps to do this, along with using an array instead of a nil-terminated list, demonstrated in new matcher collectionContainingInRelativeOrder.

**Comment by jonreid** [comment]
v5.0.0 woot
