### ISSUE TITLE
Support array literals in addition to nil-terminated lists

### ISSUE THREAD

**Issue by jonreid** [hamcrest/OCHamcrest#64]
allOf
anyOf
hasItems
containsInAnyOrder
contains
onlyContains
hasEntries
stringContainsInOrder
describedAs

**Comment by jonreid** [comment]
allOf
anyOf
hasItems
containsInAnyOrder
contains
onlyContains
stringContainsInOrder

**Comment by manumax** [comment]
I could help with this. What would be a good naming for these 'overloaded' functions?

**Comment by jonreid** [comment]
Still haven't thought of good naming…

**Comment by jonreid** [comment]
Leaning towards allOf_

**Comment by jonreid** [comment]
The ideal may be to reverse the names, so that the list above all take an array. As this would be a compatibility-breaking change, I'm shelving this for now.

The nil-terminated style could potentially take a suffix "WithObjects".

**Comment by jonreid** [comment]
First steps to do this, along with using an array instead of a nil-terminated list, demonstrated in new matcher collectionContainingInRelativeOrder.

**Comment by jonreid** [comment]
"In" matchers added to v5.0.0
