### ISSUE TITLE
how to assert subclass by OCHamcrest

### ISSUE THREAD

**Issue by zixun** [hamcrest/OCHamcrest#65]
how to assert subclass by OCHamcrest

**Comment by zixun** [comment]
superclass ,not subclass

**Comment by jonreid** [comment]
What is the question? How to test that `super` was invoked?

**Comment by zixun** [comment]
@jonreid no, I want to test if A is a superclass of B

**Comment by jonreid** [comment]
A* sut = [[A alloc] init];

    assertThat(sut, instanceOf([B class]));

(I use "sut" as the variable name of the "system under test".)
