### ISSUE TITLE
assertWithTimeout and thatEventually functions are not available in OCHamcrest-4.0.1

### ISSUE THREAD

**Issue by 4ndrey** [hamcrest/OCHamcrest#68]
I downloaded OCHamcrest-4.0.1 framework, copied to my project and added the following:
#define HC_SHORTHAND
#import <OCHamcrestIOS/OCHamcrestIOS.h>

When trying to compile my tests I got the following errors from XCode7:
Implicit declaration of function 'assertWithTimeout' is invalid in C99
Implicit declaration of function 'thatEventually' is invalid in C99

**Comment by 4ndrey** [comment]
Sorry, I used link on OCMokito page from sentence: "Prebuilt binaries are available on GitHub for OCMockito. You will also need OCHamcrest 4.0.1." and downloaded not relevant version. You probably have to update that link to proper OCHamcrest version.

**Comment by jonreid** [comment]
Ah! Thanks for letting me know… I updated the link.
