### ISSUE TITLE
OCMockito-Prefix.pch.pch: No object file for requested architecture

### ISSUE THREAD

**Issue by rcgroot** [hamcrest/OCHamcrest#69]
The iOS Framework included in the ZIP at the https://github.com/hamcrest/OCHamcrest/releases/tag/v4.3.0 seems to include from non-existing file

while processing ..../Dependencies/OCHamcrest/OCHamcrestIOS.framework/OCHamcrestIOS(HCBaseDescription.o): warning: /var/folders/84/3k6gp4_n5js57qwpk272mrhr0000gp/C/com.apple.DeveloperTools/7.0.1-7A1001/Xcode/SharedPrecompiledHeaders/OCHamcrest-Prefix-bjsliglvsggvvfdmgxqfxofiwpmx/OCHamcrest-Prefix.pch.pch: No such file or directory

**Comment by jonreid** [comment]
I'm able to take the ZIP file, and follow the directions to add OCHamcrestIOS.framework to Examples/iOSExample-Framework without any such error. However, the example project doesn't have a prefix header. Can you try tweaking the example to see if you can reproduce the problem?

**Comment by rcgroot** [comment]
The error is present in the `OCHamcrest-4.3.0/Examples/iOSExample-Framework`, right after dragging in OCHamcrestIOS.framework from the distribution zip. If you would run the example on a clean machine, not the one use for the distribution build, I suspect you will see the same issue.

For me, building from source is a workaround to the problem, but only on my machine, because then the framework contains references to files which it can find.

The OCHamcrest-Prefix.pch.pch originates from the 4.3 binaries. For example when searching the .o file:
`strings OCHamcrestIOS.framework/OCHamcrestIOS | grep pch.pch`.
Also all kinds of references to files on your machine are present in the binary. Many absolute paths starting with `/var/folders/84/3k6gp4_n5js57qwpk272mrhr0000gp`. Those /var folders don't appear in the the 4.2 binary.

**Comment by jonreid** [comment]
Oh dear, we're being bit by a "Precompiled Headers Cache Path" or SHARED_PRECOMPS_DIR. Thank you for digging into this.

**Comment by jonreid** [comment]
Try v4.3.1

**Comment by rcgroot** [comment]
The 4.3.1 release seems to fix it :+1: 

Thanks for the update!
