### ISSUE TITLE
Error that OCHamcrest.h is an incomplete umbrella header

### ISSUE THREAD

**Issue by brennantaylor** [hamcrest/OCHamcrest#72]
Cartfile contains `github "hamcrest/OCHamcrest" "v5.1.0"`

This is the first time I've compiled OCHamcrest with carthage. I get the following error when using the framework.

```text
<module-includes>:1:1: error: umbrella header for module 'OCHamcrest' does not include header 'HCBaseDescription.h' [-Werror,-Wincomplete-umbrella]
#import "/Users/brennan/project/Carthage/Build/iOS/OCHamcrest.framework/Headers/OCHamcrest.h"
^
<module-includes>:1:1: error: umbrella header for module 'OCHamcrest' does not include header 'HCCollect.h' [-Werror,-Wincomplete-umbrella]
<module-includes>:1:1: error: umbrella header for module 'OCHamcrest' does not include header 'HCRequireNonNilObject.h' [-Werror,-Wincomplete-umbrella]
<module-includes>:1:1: error: umbrella header for module 'OCHamcrest' does not include header 'HCStringDescription.h' [-Werror,-Wincomplete-umbrella]
<module-includes>:1:1: error: umbrella header for module 'OCHamcrest' does not include header 'HCWrapInMatcher.h' [-Werror,-Wincomplete-umbrella]
5 errors generated.
/Users/brennan/project/Tests/UnitTests/Resources/UnitTests-Prefix.pch:15:13: fatal error: could not build module 'OCHamcrest'
    #import <OCHamcrest/OCHamcrest.h>
     ~~~~~~~^
```

**Comment by jonreid** [comment]
Thanks for the fix. So Carthage doesn't consider transitive dependencies, apparently.

**Comment by jonreid** [comment]
…Wait, I'm positive I tested this with Carthage 0.11.0. Am I using a Carthage version that fixes the problem, or are you using a version that introduces the problem?
(The other possibility is that my testing failed.)

The need to list transitive imports feels like a Carthage bug.

**Comment by jonreid** [comment]
cc @Autoc0diq @ekurutepe

**Comment by ekurutepe** [comment]
@jonreid Carthage builds fine and does not cause any problems. You testing was fine. This problem occurs when a consumer, let's say OCMockito, uses the framework built by Carthage and imports public headers which were not included in the umbrella header for the module. In our forks we were able to resolve this either by disabling modules in the framework targets for OCHamcrest and OCMockito, or adding the all public headers to the umbrella header.

**Comment by jonreid** [comment]
Thanks
