### ISSUE TITLE
Removing the "IOS" suffix from the iOS pre-build framework.

### ISSUE THREAD

**Issue by tirodkar** [hamcrest/OCHamcrest#74]
OCHamcrest adds an “iOS” suffix for the iOS built framework. This now means that you need to import OCHamcrestIOS/OCHamcrestIOS.h to your code. However, when you change your project to use CocoaPods instead, you now find yourself having to import OCHamcrest/OCHamcrest.h since there is no “iOS” suffix there. This seems to cause problems when moving from the framework to CocoaPods, especially for large projects.

One way to handle this issue is by building OCHamcrest as [a static library and then flattening the source  ](https://softnoise.wordpress.com/2011/02/20/ios-setting-up-advanced-unit-testing-take-two/) which seems quite tedious, especially when the “IOS” suffix doesn’t seem to serve any other purpose than to distinguish it from the MacOSX Framework. Maybe we could add the frameworks in separate .zip files and not alter the code itself?

**Comment by jonreid** [comment]
Thanks for your input. I gave myself time to ponder it slowly. Upshot: I'm going to keep it the way it is.

Using the same name would make it hard to have the Mac and iOS frameworks side-by-side in the same project. That's not typical I know, but is important for the OCMockito project. And so it would impact any other cross-platform (Mac/iOS) projects that use OCHamcrest.

It is a bit of a pain to move from the prebuilt iOS version to CocoaPods. But changing the import statements can be done in a single global replacement. So the price of change is pretty low.
