### ISSUE TITLE
Remove extra semicolon in HCGenericTestFailureReporter.m

### ISSUE THREAD

**Issue by sdefresne** [hamcrest/OCHamcrest#75]
Building OCHamcrest with -Wsemicolon-before-method-body cause the following warning to be emitted by clang:

HCGenericTestFailureReporter.m:16:58: error: semicolon before method body is ignored [-Werror,-Wsemicolon-before-method-body]
- (void)executeHandlingOfFailure:(HCTestFailure *)failure;
                                                         ^

This should be as simple as removing the extra semicolon.

**Comment by jonreid** [comment]
Thanks!
