### ISSUE TITLE
HCArgumentCaptor allValues contain 2x the amount of expected values; second halve are duplicates

### ISSUE THREAD

**Issue by Nimer-88** [hamcrest/OCHamcrest#80]
-[HCArgumentCaptor allValues] will return twice the amount of expected values; halve of which will be a duplicate of previous invocations.

**Comment by Nimer-88** [comment]
Probably duplicate of https://github.com/jonreid/OCMockito/issues/123

**Comment by jonreid** [comment]
Yes, closing as duplicate
