### ISSUE TITLE
HCArgumentCaptor raises exception if the captured value does not conform to NSCopying protocol

### ISSUE THREAD

**Issue by MarcoBrescianini** [hamcrest/OCHamcrest#86]
After updating to version 7.1.0 some of my tests broke because of HCArgumentCaptor. When the matcher captures the argument passed in, it doesn't check whether the captured argument conforms to NSCopying protocol or not. The problem is due to this statement `[self.values addObject:[value copy]];` in `capture: ` method

**Comment by jonreid** [comment]
Fixed. Thank you for reporting this, that was pretty bad!

**Comment by MarcoBrescianini** [comment]
Thank you @jonreid!
