### ISSUE TITLE
New date matcher

### ISSUE THREAD

**Issue by adib** [hamcrest/OCHamcrest#93]
I have a new custom matcher class to compare `NSDate` objects. It is a variation of `HCIsCloseTo` and uses `NSDate` for the value with `NSTimeInterval` for the delta.

```objc

@interface HCIsDateCloseTo : HCBaseMatcher


- (instancetype)initWithValue:(NSDate*)date delta:(NSTimeInterval)delta NS_DESIGNATED_INITIALIZER;

- (instancetype)init NS_UNAVAILABLE;

@end

```

Are you interested in integrating this into OCHamcrest's main code tree? I can send a pull request if you do.

**Comment by jonreid** [comment]
Wow, I'm glad someone is still using OCHamcrest!
But I'd rather not make another release unless there is greater demand.
